/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import models.Customer;
import models.DBManager;
import models.Order;
import models.OrderLine;
import models.Staff;
import models.ViewUtils;
/**
 *
 * @author manue
 */
public class StaffPreviousOrderLines extends javax.swing.JFrame {
    
    //global variables
    private Staff loggedInStaff;
    private int orderId;

    /**
     * Creates new form CustomerPreviousOrderLines
     */
    public StaffPreviousOrderLines(Staff staff, int orderIdIn) {

        loggedInStaff=staff;
        orderId = orderIdIn;
        initComponents();
        ViewUtils.setStandardSize(this);
        this.pack();
        //initializing DBManager
        DBManager db = new DBManager();
        //creating hashmap -loading zookeepers from the database
        HashMap<String, Customer> customers = db.loadCustomers();
        //initializing Order instance
        Order order = new Order();
        //looping through all the ZooKeeper records
        for(Map.Entry<String, Customer> cEntry : customers.entrySet())
        {   
            Customer customer = cEntry.getValue();
            //checking conditions - orderId
            if(customer.getOrders().containsKey(orderId))
            {   //getting the desired order
                order = customer.getOrders().get(orderId);
            }
        }
        //initialising a DefaultTableModel object
        DefaultTableModel basketModel = (DefaultTableModel)tblOrderLines.getModel();
        //for loop through each Orderline inside currentOrder, to fill up the table
        for(Map.Entry<Integer, OrderLine> olEntry : order.getOrderLines().entrySet())
        {   //initialising Orderline object to get the values
            OrderLine orderLine = olEntry.getValue();
            //adding values to the rows
            basketModel.addRow( new Object[] {
            orderLine.getProduct().getProductId(),
            orderLine.getProduct().getProductName(), "£" +
            String.format("%.02f", orderLine.getProduct().getPrice()),
            orderLine.getQuantity(),
            String.format("%.02f", orderLine.getLineTotal())
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderLines = new javax.swing.JTable();
        btnReturnToOrders = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblOrderLines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductId", "Product", "Price per Item", "Quantity", "Total Price per Item"
            }
        ));
        jScrollPane1.setViewportView(tblOrderLines);

        btnReturnToOrders.setText("Return to Orders");
        btnReturnToOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReturnToOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnReturnToOrders)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnToOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToOrdersActionPerformed

        //calling the desired page, passing loggedInZookeeper
        StaffViewOrders staffViewOrders = new StaffViewOrders(loggedInStaff);
        this.dispose(); //closing the current page
        staffViewOrders.setVisible(true); //showing the desired page  
    }//GEN-LAST:event_btnReturnToOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffPreviousOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffPreviousOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffPreviousOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffPreviousOrderLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           //     new CustomerPreviousOrderLines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnToOrders;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JTable tblOrderLines;
    // End of variables declaration//GEN-END:variables
}
