/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import models.Staff;
import models.DBManager;
import models.Order;
import models.Customer;
import models.ViewUtils;

/**
 *
 * @author manue
 */
public class StaffViewOrders extends javax.swing.JFrame {
    
    private Staff loggedInStaff;

    /**
     * Creates new form StaffViewOrders
     */
    public StaffViewOrders(Staff staffIn) {
        loggedInStaff = staffIn;
        initComponents();
        this.pack();
        ViewUtils.setStandardSize(this);
        //initialising a DefaultTableModel object
        DefaultTableModel ordersModel = (DefaultTableModel)tblOrder.getModel();
        DBManager db = new DBManager();
        //initializing allCustomer Hashmap, through db.LoadCustomers
        HashMap<String, Customer> allCustomers= db.loadCustomers();
        //for loop, looping through our customers entries
        for(Map.Entry<String, Customer> cEntry : allCustomers.entrySet())
        {   //initializing actualCustomer object, basically one object for each customer entry
            Customer actualCustomer= cEntry.getValue();
            //for loop, looping through every customer's orders
            for(Map.Entry<Integer, Order> oEntry : actualCustomer.getOrders().entrySet())
            {   //getting values for each order
                Order actualOrder = oEntry.getValue();
                //adding rows to our table
                ordersModel.addRow(new Object[]{
                    actualCustomer.getUserName(),
                    actualOrder.getOrderId(),
                    new SimpleDateFormat("dd/MM/yyyy").format(actualOrder.getOrderDate()),
                    "£" + String.format("%.02f", actualOrder.getOrderTotal()),
                    actualOrder.getStatus()
                });
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewOrderDetails = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Order Id", "Date", "Total", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblOrder);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewOrderDetails.setText("View Order Details for Selected Order");
        btnViewOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnViewOrderDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBack)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewOrderDetails)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        //intializing StaffHome object
        StaffHome staffHome  = new StaffHome(loggedInStaff);
        staffHome.setVisible(true); //setting desired page as Visible
        this.dispose(); //closing current page
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderDetailsActionPerformed
        // TODO add your handling code here:
        
        //getting the index of the selected row
        int selectedRow = tblOrder.getSelectedRow();
        //error case: no order has been selected
        if (selectedRow == -1)
        {   //setting error message
            lblErrorMessage.setText("Error: no Order selected");
        }
        else
        {
            //we get the id we want: we need to convert the object into a value
            int orderId = (int)tblOrder.getValueAt(selectedRow, 1);
            
        //calling the desired page, passing the required parameters
        StaffPreviousOrderLines staffPreviousOrderLines = new StaffPreviousOrderLines(loggedInStaff, orderId);
        this.dispose(); //closing the current page
        staffPreviousOrderLines.setVisible(true); //showing the desired page
        }        
    }//GEN-LAST:event_btnViewOrderDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffViewOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new StaffViewOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewOrderDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JTable tblOrder;
    // End of variables declaration//GEN-END:variables
}
